Repository DongHyeonDev/Duriso, pull requests merged in 2024-09, with the labels that each got.

#57 Feat: 셀버튼 이벤트 생성 / Design: 셀 클릭시 UI생성
  Duriso.xcodeproj/project.pbxproj
  Duriso/Model/Board/BoardModel.swift
  Duriso/Model/Guideline/GuidelineModel.swift
  Duriso/View/Board/BoardTableViewCell.swift
  Duriso/View/Board/BoardViewController.swift
  Duriso/View/Board/CategoryCell.swift
  Duriso/View/Board/PostViewController.swift
  Duriso/View/Board/PostingViewController.swift
  Duriso/ViewModel/Board/BoardViewModel.swift
Labels: :sparkles: Feat, :lipstick: Design, 신상규

#60 Feature/onlinemap
  Duriso.xcodeproj/project.pbxproj
  Duriso/Assets/Assets.xcassets/MapTypeIcon/Contents.json
  Duriso/Assets/Assets.xcassets/MapTypeIcon/bolt.heart.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/MapTypeIcon/bolt.heart.imageset/bolt.heart.png
  Duriso/Assets/Assets.xcassets/MapTypeIcon/figure.run.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/MapTypeIcon/figure.run.imageset/figure.run.png
  Duriso/Assets/Assets.xcassets/MapTypeIcon/megaphone.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/MapTypeIcon/megaphone.imageset/megaphone.png
  Duriso/Model/OnlineMap/EmergencyReportData.swift
  Duriso/Model/OnlineMap/OnlineMapModel.swift
  Duriso/Network/NetworkManager.swift
  Duriso/Network/OnlineMapNetworkManager/AedNetworkManager.swift
  Duriso/Network/OnlineMapNetworkManager/ShelterNetworkManager.swift
  Duriso/View/OnlineMap/BottomsheetView/AedViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/EmergencyReportViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/MapBottomSheetViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/ShelterViewController.swift
  Duriso/View/OnlineMap/EmergencyReportViewController.swift
  Duriso/View/OnlineMap/KakaoMapViewController.swift
  Duriso/View/OnlineMap/MapBottomSheetViewController.swift
  Duriso/View/OnlineMap/OnlineViewController.swift
  Duriso/ViewModel/OnlineMap/OnlineViewModel.swift
  Duriso/ViewModel/OnlineMap/PoiViewModel.swift
Labels: :bug: Bug, :sparkles: Feat, :lipstick: Design, :package:Chore, 이주희, :heavy_plus_sign:add

#64 feature/offlinemap to develop PR
  Duriso.xcodeproj/project.pbxproj
  Duriso/Common/FirebaseFirestoreManager.swift
  Duriso/Info.plist
  Duriso/Model/OfflineMap/LocationModel.swift
  Duriso/View/MainTabBarViewController.swift
  Duriso/View/OfflineMap/OfflineMapViewController.swift
  Duriso/View/OfflineMap/OfflineViewController.swift
  Duriso/ViewModel/OfflineMap/OfflineMapViewModel.swift
Labels: :sparkles: Feat, :package: Chore, 김동현

#67 Feat: Firebase Storage, Database연동 및 위치Label자동 변경
  Duriso.xcodeproj/project.pbxproj
  Duriso/Common/FirebaseFirestoreManager.swift
  Duriso/Model/Board/BoardModel.swift
  Duriso/Model/OnlineMap/RegionFetcher.swift
  Duriso/View/Board/BoardCollectionViewCell.swift
  Duriso/View/Board/BoardTableViewCell.swift
  Duriso/View/Board/BoardViewController.swift
  Duriso/View/Board/CategoryCell.swift
  Duriso/View/Board/PostChangeViewController.swift
  Duriso/View/Board/PostViewController.swift
  Duriso/View/Board/PostingViewController.swift
  Duriso/View/OnlineMap/KakaoMapViewController.swift
  Duriso/View/OnlineMap/OnlineViewController.swift
  Duriso/ViewModel/Board/BoardFirebaseService.swift
Labels: :sparkles: Feat, 신상규, :adhesive_bandage: Fix

#70 Feature/onlinemap
  Duriso.xcodeproj/project.pbxproj
  Duriso/App/AppDelegate.swift
  Duriso/Model/OnlineMap/EmergencyReportModel.swift
  Duriso/Model/OnlineMap/OnlineMapModel.swift
  Duriso/Network/NetworkManager.swift
  Duriso/Network/OnlineMapNetworkManager/AedNetworkManager.swift
  Duriso/View/OnlineMap/BottomsheetView/AedViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/EmergencWrittingViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/EmergencyReportViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/MapBottomSheetViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/ShelterViewController.swift
  Duriso/View/OnlineMap/KakaoMapViewController.swift
  Duriso/View/OnlineMap/OnlineViewController.swift
  Duriso/ViewModel/OnlineMap/OnlineViewModel.swift
  Duriso/ViewModel/OnlineMap/PoiViewModel.swift
Labels: :sparkles: Feat, :lipstick: Design, 이주희

#71 Feat: tableView PDFkit 삽입, 긴급재난문자API연결 /Disign: UI위치 변경
  Duriso.xcodeproj/project.pbxproj
  Duriso/Common/Environment.swift
  Duriso/Info.plist
  Duriso/Model/Guideline/GuidelineModel.swift
  Duriso/Network/GuidelineNetWork.swift
  Duriso/View/Guideline/GuidelineKitView.swift
  Duriso/View/Guideline/GuidelinePDFViewController.swift
  Duriso/View/Guideline/GuidelineViewController.swift
  Duriso/ViewModel/Guideline/GuidelineTableViewModel.swift
  Duriso/ViewModel/Guideline/GuidelineViewModel.swift
Labels: :sparkles: Feat, :lipstick: Design, 신상규

#72 Feature/onlinemap: 긴급제보 기능
  Duriso.xcodeproj/project.pbxproj
  Duriso/Model/OnlineMap/EmergencyReportModel.swift
  Duriso/View/OnlineMap/BottomsheetView/AedViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/EmergencWrittingViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/EmergencyReportViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/EmergencyWrittingViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/ShelterViewController.swift
  Duriso/View/OnlineMap/OnlineViewController.swift
  Duriso/ViewModel/Board/BoardViewModel.swift
  Duriso/ViewModel/OnlineMap/PoiViewModel.swift
Labels: :sparkles: Feat, :lipstick: Design, 이주희

#73 Design: safeAreaLayoutGuide, Alert버튼 위치변경
  Duriso/View/Board/PostViewController.swift
  Duriso/View/Board/PostingViewController.swift
Labels: :lipstick: Design, 신상규

#75 Feature/login
  Duriso.xcodeproj/project.pbxproj
  Duriso/Model/MyPage/NoticeModel.swift
  Duriso/Model/SignUp/SignUpModel.swift
  Duriso/View/LoginView/LoginViewController.swift
  Duriso/View/LoginView/SignUpViewController.swift
  Duriso/View/MyPage/ChangePasswordViewController.swift
  Duriso/View/MyPage/LegalNoticeDetailViewController.swift
  Duriso/View/MyPage/LegalNoticeViewController.swift
  Duriso/View/MyPage/ModifyInformationViewController.swift
  Duriso/View/MyPage/MyPageViewController.swift
  Duriso/View/MyPage/NoticeDetailViewController.swift
  Duriso/View/MyPage/NoticeTableViewCell.swift
  Duriso/View/MyPage/NoticeViewController.swift
  Duriso/ViewModel/Login/SignUpViewModel.swift
  Duriso/ViewModel/MyPage/MyPageViewModel.swift
  Duriso/ViewModel/MyPage/NoticeViewModel.swift
Labels: :sparkles: Feat, :lipstick: Design, 조수환

#78 Design: Layout & Constraints 수정
  Duriso/Model/Board/BoardModel.swift
  Duriso/View/Board/BoardCollectionViewCell.swift
  Duriso/View/Board/BoardViewController.swift
  Duriso/View/Guideline/GuidelineViewController.swift
  Duriso/View/MyPage/MyPageViewController.swift
Labels: :lipstick: Design, 김동현

#79 Feature/onlinemap 탭바 아이콘 수정
  Duriso.xcodeproj/project.pbxproj
  Duriso/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  Duriso/Assets/Assets.xcassets/AppIcon.appiconset/Duriso.png
  Duriso/Assets/Assets.xcassets/AppIcon.appiconset/icon.png
  Duriso/Assets/Assets.xcassets/TabBarIcon/Contents.json
  Duriso/Assets/Assets.xcassets/TabBarIcon/DocsIcon.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/TabBarIcon/DocsIcon.imageset/DocsIcon.png
  Duriso/Assets/Assets.xcassets/TabBarIcon/MapIcon.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/TabBarIcon/MapIcon.imageset/MapIcon.png
  Duriso/Assets/Assets.xcassets/TabBarIcon/UserIcon.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/TabBarIcon/UserIcon.imageset/UserIcon.png
  Duriso/Assets/Assets.xcassets/TabBarIcon/communityIcon.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/TabBarIcon/communityIcon.imageset/communityIcon.png
  Duriso/Assets/Assets.xcassets/logo.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/logo.imageset/logo@1x.png
  Duriso/Assets/Assets.xcassets/logo.imageset/logo@2x.png
  Duriso/Assets/Assets.xcassets/logo.imageset/logo@3x.png
  Duriso/Base.lproj/LaunchScreen.storyboard
  Duriso/Extensions/Font+Extensions.swift
  Duriso/Extensions/UIColor+Extensions.swift
  Duriso/Model/Board/BoardModel.swift
  Duriso/Model/OnlineMap/OnlineMapModel.swift
  Duriso/Network/NetworkManager.swift
  Duriso/Network/OnlineMapNetworkManager/AedDataManager.swift
  Duriso/Network/OnlineMapNetworkManager/AedNetworkManager.swift
  Duriso/Network/OnlineMapNetworkManager/ShelterNetworkManager.swift
  Duriso/View/MainTabBarViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/AedViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/EmergencyReportViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/EmergencyWrittingViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/MapBottomSheetViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/ShelterViewController.swift
  Duriso/View/OnlineMap/KakaoMapViewController.swift
  Duriso/View/OnlineMap/OnlineViewController.swift
  Duriso/ViewModel/OnlineMap/OnlineViewModel.swift
  Duriso/ViewModel/OnlineMap/PoiViewModel.swift
Labels: :lipstick: Design, 이주희, :heavy_plus_sign: add

#80 feature/offlinemap to develop PR
  Duriso/App/SceneDelegate.swift
  Duriso/Model/Board/BoardModel.swift
  Duriso/View/Guideline/GuidelinePDFViewController.swift
  Duriso/View/LoginView/SignUpViewController.swift
  Duriso/View/MainTabBarViewController.swift
Labels: :sparkles: Feat, :truck: Rename, 김동현, :adhesive_bandage: Fix

#81 Feature/login
  Duriso/Data/LegalNotice/notice1.txt
  Duriso/Data/LegalNotice/notice2.txt
  Duriso/Data/LegalNotice/notice3.txt
  Duriso/View/MyPage/MyPageViewController.swift
  Duriso/ViewModel/MyPage/LegalNoticeViewModel.swift
Labels: :memo: Docs, :lipstick: Design, 조수환

#82 Feat: 게시글 수정, 삭제, 신고1회 기능 추가
  Duriso/Model/Board/BoardModel.swift
  Duriso/View/Board/BoardCollectionViewCell.swift
  Duriso/View/Board/BoardViewController.swift
  Duriso/View/Board/PostingViewController.swift
  Duriso/ViewModel/Board/BoardViewModel.swift
Labels: :sparkles: Feat

#83 Fix: pbxproj 중복파일 제거 및 오타 수정
  Duriso.xcodeproj/project.pbxproj
  Duriso/View/Board/BoardViewController.swift
Labels: :ambulance: !HOTFIX, 김동현

#84 Feature/onlinemap
  Duriso/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  Duriso/Assets/Assets.xcassets/AppIcon.appiconset/icon.png
  Duriso/Assets/Assets.xcassets/AppIcon.appiconset/logo6.png
  Duriso/Assets/Assets.xcassets/delete.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/delete.imageset/delete.png
  Duriso/Assets/Assets.xcassets/edit.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/edit.imageset/edit.png
  Duriso/Assets/Assets.xcassets/trash.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/trash.imageset/trash.png
  Duriso/Base.lproj/LaunchScreen.storyboard
  Duriso/View/Board/BoardTableViewCell.swift
  Duriso/View/Board/BoardViewController.swift
  Duriso/View/Board/PostChangeViewController.swift
  Duriso/View/Board/PostViewController.swift
  Duriso/View/Board/PostingViewController.swift
  Duriso/View/Guideline/GuidelineFlowLayout.swift
  Duriso/View/Guideline/GuidelineViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/EmergencyWrittingViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/MapBottomSheetViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/ShelterViewController.swift
Labels: :lipstick: Design, 이주희, :heavy_plus_sign: add

#85 Fix: 로그인 실패 시 로그인버튼 미작동 오류 해결
  Duriso/ViewModel/Login/LoginViewModel.swift
Labels: 조수환, :adhesive_bandage: Fix

#86 Fix: 주소 미표기 해결
  Duriso/View/Board/BoardTableViewCell.swift
Labels: 신상규, :adhesive_bandage: Fix

#87 Docs: 저작권 표시 추가
  Duriso.xcodeproj/project.pbxproj
  Duriso/Data/Copyrights/api.txt
  Duriso/Data/Copyrights/imagedocument.txt
  Duriso/Data/Copyrights/maplibre.txt
  Duriso/Data/Copyrights/notoSans.txt
  Duriso/Data/LegalNotice/notice1.txt
  Duriso/Data/LegalNotice/notice2.txt
  Duriso/Data/LegalNotice/notice3.txt
  Duriso/Model/MyPage/CopyrightModel.swift
  Duriso/View/Guideline/GuidelineViewController.swift
  Duriso/View/MyPage/CopyrightDetailViewController.swift
  Duriso/View/MyPage/CopyrightTableViewCell.swift
  Duriso/View/MyPage/CopyrightViewController.swift
  Duriso/View/MyPage/MyPageViewController.swift
  Duriso/ViewModel/Guideline/GuidelineViewModel.swift
  Duriso/ViewModel/MyPage/CopyrightViewModel.swift
  Duriso/ViewModel/MyPage/MyPageViewModel.swift
Labels: :memo: Docs, 김동현

#91 Hotfix
  .gitignore
  Duriso.xcodeproj/project.pbxproj
  Duriso.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Duriso/Assets/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  Duriso/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  Duriso/Assets/Assets.xcassets/AppIcon.appiconset/logo6.png
  Duriso/Info.plist
  Duriso/View/MyPage/ChangePasswordViewController.swift
  Duriso/View/MyPage/ModifyInformationViewController.swift
  Duriso/View/MyPage/MyPageViewController.swift
Labels: :ambulance: !HOTFIX, 김동현, 조수환

#92 Hotfix
  Duriso.xcodeproj/project.pbxproj
  Duriso/Assets/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  Duriso/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  Duriso/Assets/Assets.xcassets/AppIcon.appiconset/logo6.png
  Duriso/Info.plist
  Duriso/View/MyPage/ChangePasswordViewController.swift
  Duriso/View/MyPage/ModifyInformationViewController.swift
  Duriso/View/MyPage/MyPageViewController.swift
Labels: :ambulance: !HOTFIX, 김동현, 조수환

#94 Feat: 카메라 Alert변경, 내용수정, userNickName추가
  Duriso/Info.plist
  Duriso/View/Board/PostingViewController.swift
Labels: :sparkles: Feat, 신상규

#95 Feat: 회원가입 진행 시 이용약관 확인 구현
  Duriso.xcodeproj/project.pbxproj
  Duriso/View/LoginView/SignUpViewController.swift
  Duriso/View/LoginView/SignUptableViewCell.swift
  Duriso/View/MyPage/ChangePasswordViewController.swift
  Duriso/View/MyPage/LegalNoticeViewController.swift
  Duriso/View/MyPage/ModifyInformationViewController.swift
Labels: :sparkles: Feat, 조수환

#97 Design: 마이페이지 문의 메일 추가, 로그아웃 구현
  Duriso/View/MyPage/MyPageViewController.swift
Labels: :sparkles: Feat, :lipstick: Design, 조수환

#98 hotfix to develop PR
  Duriso.xcodeproj/project.pbxproj
Labels: :ambulance: !HOTFIX

#99 Hotfix
  Duriso.xcodeproj/project.pbxproj
  Duriso/View/MyPage/MyPageViewController.swift
Labels: :ambulance: !HOTFIX

#100 Feat: 좋아요 기능 Firebase저장
  Duriso/View/Board/PostViewController.swift
  Duriso/View/Board/PostingViewController.swift
Labels: :sparkles: Feat, 신상규

#101 develop to main PR
  Duriso/View/Board/PostViewController.swift
  Duriso/View/Board/PostingViewController.swift
  Duriso/View/MyPage/MyPageViewController.swift
Labels: :sparkles: Feat

#102 Feature/onlinemap
  Duriso/Assets/Assets.xcassets/Community/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Earthquaketag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Earthquaketag.imageset/Earthquake.png
  Duriso/Assets/Assets.xcassets/Community/EmergencyReporttag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/EmergencyReporttag.imageset/EmergencyReport.png
  Duriso/Assets/Assets.xcassets/Community/Floodtag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Floodtag.imageset/Flood.png
  Duriso/Assets/Assets.xcassets/Community/ForestFirestag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/ForestFirestag.imageset/ForestFires.png
  Duriso/Assets/Assets.xcassets/Community/Heatwavetag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Heatwavetag.imageset/Heatwave.png
  Duriso/Assets/Assets.xcassets/Community/HeavySnowtag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/HeavySnowtag.imageset/HeavySnow.png
  Duriso/Assets/Assets.xcassets/Community/Landslidetag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Landslidetag.imageset/Landslide.png
  Duriso/Assets/Assets.xcassets/Community/Nucleartag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Nucleartag.imageset/Nuclear.png
  Duriso/Assets/Assets.xcassets/Community/Tsunamitag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Tsunamitag.imageset/Tsunami.png
  Duriso/Assets/Assets.xcassets/Community/Typhoontag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Typhoontag.imageset/Typhoon.png
  Duriso/View/OnlineMap/BottomsheetView/EmergencyReportViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/EmergencyWrittingViewController.swift
  Duriso/View/OnlineMap/OnlineViewController.swift
Labels: :lipstick: Design, 이주희

#103 Feat: 자동 로그인 구현
  Duriso/View/LoginView/LoginViewController.swift
  Duriso/View/MyPage/MyPageViewController.swift
Labels: :sparkles: Feat, 조수환

#104 Feat: 차단기능 추가
  Duriso/View/Board/BoardViewController.swift
  Duriso/View/Board/PostingViewController.swift
Labels: :sparkles: Feat, 신상규

#105 Chore: Build Number 갱신
  Duriso.xcodeproj/project.pbxproj
Labels: :package: Chore, 김동현

#106 hotfix to main PR
  Duriso.xcodeproj/project.pbxproj
  Duriso/Assets/Assets.xcassets/Community/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Earthquaketag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Earthquaketag.imageset/Earthquake.png
  Duriso/Assets/Assets.xcassets/Community/EmergencyReporttag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/EmergencyReporttag.imageset/EmergencyReport.png
  Duriso/Assets/Assets.xcassets/Community/Floodtag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Floodtag.imageset/Flood.png
  Duriso/Assets/Assets.xcassets/Community/ForestFirestag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/ForestFirestag.imageset/ForestFires.png
  Duriso/Assets/Assets.xcassets/Community/Heatwavetag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Heatwavetag.imageset/Heatwave.png
  Duriso/Assets/Assets.xcassets/Community/HeavySnowtag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/HeavySnowtag.imageset/HeavySnow.png
  Duriso/Assets/Assets.xcassets/Community/Landslidetag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Landslidetag.imageset/Landslide.png
  Duriso/Assets/Assets.xcassets/Community/Nucleartag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Nucleartag.imageset/Nuclear.png
  Duriso/Assets/Assets.xcassets/Community/Tsunamitag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Tsunamitag.imageset/Tsunami.png
  Duriso/Assets/Assets.xcassets/Community/Typhoontag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Typhoontag.imageset/Typhoon.png
  Duriso/View/Board/BoardViewController.swift
  Duriso/View/Board/PostingViewController.swift
  Duriso/View/LoginView/LoginViewController.swift
  Duriso/View/MyPage/MyPageViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/EmergencyReportViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/EmergencyWrittingViewController.swift
  Duriso/View/OnlineMap/OnlineViewController.swift
Labels: :sparkles: Feat, :lipstick: Design, :package: Chore, :ambulance: !HOTFIX, 이주희, 김동현, 조수환, 신상규, :heavy_plus_sign: add

#107 Fix: 최신순 반대로 나오는 버그 수정
  Duriso/View/Board/BoardViewController.swift
Labels: 신상규, :adhesive_bandage: Fix

#108 Refactor: 변수명 클래스명 변경/Feat: Image 킹피셔 적용, 유저nil일시 Alert
  Duriso.xcodeproj/project.pbxproj
  Duriso/View/Board/BoardCollectionViewCell.swift
  Duriso/View/Board/BoardTableViewCell.swift
  Duriso/View/Board/BoardViewController.swift
  Duriso/View/Board/EditPostViewController.swift
  Duriso/View/Board/UserPostViewController.swift
  Duriso/View/Board/WritingViewController.swift
Labels: :recycle: Refactor, :sparkles: Feat, 신상규

#110 Feat: 비회원으로 둘러보기, 회원 탈퇴 구현, 자동 로그인 오류 수정
  Duriso.xcodeproj/project.pbxproj
  Duriso/View/Board/BoardViewController.swift
  Duriso/View/Board/UserPostViewController.swift
  Duriso/View/LoginView/LoginViewController.swift
  Duriso/View/MyPage/MuteTableViewCell.swift
  Duriso/View/MyPage/MuteViewController.swift
  Duriso/View/MyPage/MyPageViewController.swift
  Duriso/ViewModel/Login/SignUpViewModel.swift
  Duriso/ViewModel/MyPage/MuteViewModel.swift
  Duriso/ViewModel/MyPage/MyPageViewModel.swift
Labels: :sparkles: Feat, 조수환, :adhesive_bandage: Fix

#111 hotfix to develop PR
  Duriso.xcodeproj/project.pbxproj
  Duriso/Assets/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  Duriso/Assets/Assets.xcassets/logo.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/logo.imageset/logo.png
  Duriso/Assets/Assets.xcassets/logo.imageset/logo@1x.png
  Duriso/Assets/Assets.xcassets/logo.imageset/logo@2x.png
  Duriso/Assets/Assets.xcassets/logo.imageset/logo@3x.png
  Duriso/Base.lproj/LaunchScreen.storyboard
  Duriso/View/Board/BoardViewController.swift
  Duriso/View/LoginView/LoginViewController.swift
  Duriso/View/MyPage/MyPageViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/EmergencyReportViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/EmergencyWrittingViewController.swift
  Duriso/View/OnlineMap/OnlineViewController.swift
Labels: :ambulance: !HOTFIX, 김동현

#113 Design: Cell image 없으면 Label위치 변경
  Duriso/View/Board/BoardTableViewCell.swift
Labels: :lipstick: Design, 신상규
