Repository DongHyeonDev/Duriso, pull requests merged in 2024-10, with the labels that each got.

#114 Feat: 제목, 내용이 nil일시 Alert 띄우기
  Duriso/View/Board/WritingViewController.swift
Labels: :sparkles: Feat, 신상규

#115 Design: 행동요령 UI변경
  Duriso/Model/Board/BoardModel.swift
  Duriso/Model/Guideline/GuidelineModel.swift
  Duriso/View/Guideline/GuidelineTableViewCell.swift
  Duriso/View/Guideline/GuidelineViewController.swift
  Duriso/ViewModel/Guideline/GuidelineTableViewModel.swift
Labels: :lipstick: Design, 신상규

#116 Feat: 자기차단 불가, 자기신고 불가, 카테고리 미적용 얼럿, 게시글추가시 카운트1 증가
  Duriso.xcodeproj/project.pbxproj
  Duriso/View/Board/BoardViewController.swift
  Duriso/View/Board/UserPostViewController.swift
  Duriso/View/Board/WritingViewController.swift
  Duriso/View/OfflineMap/BoardCollectionViewCell.swift
Labels: :sparkles: Feat, 신상규

#119 Docs: README.md 파일 작성
  README.md
Labels: :memo: Docs, 김동현

#120 Docs: README.md 파일 작성
  .github/ISSUE_TEMPLATE/agenda-template.md
  .github/ISSUE_TEMPLATE/bug-report-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  README.md
Labels: :memo: Docs, 김동현

#121 Release (V. 1.0.3)
  Duriso.xcodeproj/project.pbxproj
  Duriso/Base.lproj/LaunchScreen.storyboard
Labels: 김동현, :iphone: Release

#122 Release (V. 1.0.3)
  Duriso.xcodeproj/project.pbxproj
  Duriso/Base.lproj/LaunchScreen.storyboard
  Duriso/Model/Board/BoardModel.swift
  Duriso/Model/Guideline/GuidelineModel.swift
  Duriso/View/Board/BoardTableViewCell.swift
  Duriso/View/Board/BoardViewController.swift
  Duriso/View/Board/UserPostViewController.swift
  Duriso/View/Board/WritingViewController.swift
  Duriso/View/Guideline/GuidelineTableViewCell.swift
  Duriso/View/Guideline/GuidelineViewController.swift
  Duriso/View/OfflineMap/BoardCollectionViewCell.swift
  Duriso/ViewModel/Guideline/GuidelineTableViewModel.swift
Labels: 김동현, :iphone: Release

#125 Feature/onlinemap, UserpostView UI 수정
  Duriso/Assets/Assets.xcassets/Community/Earthquaketag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Earthquaketag.imageset/Earthquake.png
  Duriso/Assets/Assets.xcassets/Community/Earthquaketag.imageset/Earthquaketag.png
  Duriso/Assets/Assets.xcassets/Community/EmergencyReporttag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/EmergencyReporttag.imageset/EmergencyReport.png
  Duriso/Assets/Assets.xcassets/Community/EmergencyReporttag.imageset/EmergencyReporttag.png
  Duriso/Assets/Assets.xcassets/Community/Floodtag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Floodtag.imageset/Flood.png
  Duriso/Assets/Assets.xcassets/Community/Floodtag.imageset/Floodtag.png
  Duriso/Assets/Assets.xcassets/Community/ForestFirestag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/ForestFirestag.imageset/ForestFires.png
  Duriso/Assets/Assets.xcassets/Community/ForestFirestag.imageset/ForestFirestag.png
  Duriso/Assets/Assets.xcassets/Community/Heatwavetag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Heatwavetag.imageset/Heatwave.png
  Duriso/Assets/Assets.xcassets/Community/Heatwavetag.imageset/Heatwavetag.png
  Duriso/Assets/Assets.xcassets/Community/HeavySnowtag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/HeavySnowtag.imageset/HeavySnow.png
  Duriso/Assets/Assets.xcassets/Community/HeavySnowtag.imageset/HeavySnowtag.png
  Duriso/Assets/Assets.xcassets/Community/Landslidetag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Landslidetag.imageset/Landslide.png
  Duriso/Assets/Assets.xcassets/Community/Landslidetag.imageset/Landslidetag.png
  Duriso/Assets/Assets.xcassets/Community/Nucleartag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Nucleartag.imageset/Nuclear.png
  Duriso/Assets/Assets.xcassets/Community/Nucleartag.imageset/Nucleartag.png
  Duriso/Assets/Assets.xcassets/Community/Tsunamitag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Tsunamitag.imageset/Tsunami.png
  Duriso/Assets/Assets.xcassets/Community/Tsunamitag.imageset/Tsunamitag.png
  Duriso/Assets/Assets.xcassets/Community/Typhoontag.imageset/Contents.json
  Duriso/Assets/Assets.xcassets/Community/Typhoontag.imageset/Typhoon.png
  Duriso/Assets/Assets.xcassets/Community/Typhoontag.imageset/Typhoontag.png
  Duriso/View/Board/BoardViewController.swift
  Duriso/View/Board/UserPostViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/AedViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/EmergencyReportViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/EmergencyWrittingViewController.swift
  Duriso/View/OnlineMap/BottomsheetView/ShelterViewController.swift
Labels: :lipstick: Design
